name: linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Backend (Laravel)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" # note: PHP 8.4 n'existe pas encore (à mai 2025)

      - name: Install backend dependencies
        working-directory: ./api
        run: composer install --no-interaction --prefer-dist

      - name: Run Laravel Pint (PHP linter)
        working-directory: ./api
        run: vendor/bin/pint

      # Frontend (Vue + Vite)
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # ou la version que tu utilises

      - name: Install frontend dependencies
        working-directory: ./client
        run: pnpm install

      - name: Format frontend code
        working-directory: ./client
        run: pnpm run format

      - name: Lint frontend code
        working-directory: ./client
        run: pnpm run lint

      # Auto-commit (optional)
      # - name: Commit code style fixes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: fix code style
      #     commit_options: '--no-verify'
